pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'weatherly-app'
        // Since we are running locally, we'll just tag it for the local engine
        IMAGE_TAG = "latest"
    }

    stages {
        stage('Checkout') {
            steps {
                // For local WSL testing, we assume the code is already there or checked out
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    def scannerHome = tool 'SonarScanner'
                    withSonarQubeEnv('SonarQube') {
                        sh "${scannerHome}/bin/sonar-scanner"
                    }
                }
            }
        }

        stage('Build') {
            steps {
                sh 'npm run build'
            }
        }

        stage('Docker Build & Tag') {
            steps {
                script {
                    // Ensure the jenkins user can access the docker socket
                    sh "docker build -t ${DOCKER_IMAGE}:${IMAGE_TAG} ."
                    sh "docker tag ${DOCKER_IMAGE}:${IMAGE_TAG} ${DOCKER_IMAGE}:backup"
                }
            }
        }

        stage('Deploy Local') {
            steps {
                // Trigger Ansible for local deployment
                sh 'ansible-playbook -i ansible/inventory ansible/playbook.yml'
            }
        }
    }
}
