---
- name: Deploy Weatherly Application Locally
  hosts: localhost
  connection: local

  tasks:
    - name: Stop and remove existing container
      docker_container:
        name: weatherly
        state: absent

    - name: Run the latest Weatherly container
      docker_container:
        name: weatherly
        image: weatherly-app:latest
        state: started
        restart: yes
        ports:
          - "80:80"
        networks:
          - name: devops-network
